# Run with:
# ansible-playbook InstallCertBot.yml

---
- name: Install CertBot
  hosts: all
  tasks:

  - name: Install Certbot package on OpenSUSE/SUSE Linux
    zypper:
      name: python311-certbot
      state: present

  - name: Install Certbot Apache Plugin package on OpenSUSE/SUSE Linux
    zypper:
      name: python311-certbot-apache
      state: present

#  - name: Accept TOS and register
#    shell: certbot --agree-tos --apache -m ajorians@gmail.com -n
