# Run with:
# ansible-playbook InstallMLocate.yml

---
- name: Install MLocate
  hosts: all
  tasks:

  - name: Install MLocate package on OpenSUSE/SUSE Linux
    zypper:
      name: mlocate
      state: present
