# Run with:
# ansible-playbook SetMediaWikiLogo.yml

---
- name: Set MediaWiki Logo
  hosts: all
  tasks:

  - name: Check if MediaWiki already setup
    stat:
      path: /srv/www/htdocs/mediawiki-1.39.3/LocalSettings.php
    register: localsettings_exists

  - name: Message if MediaWiki not already setup
    debug:
        msg: "Need to setup MediaWiki before installing extension"
    when: localsettings_exists.stat.exists == false

  - name: End the play if MediaWiki not already setup
    ansible.builtin.meta: end_play
    when: localsettings_exists.stat.exists == false

# TODO: Download logo from a central spot
#  - name: check if logo exists
#    stat:
#      path: /srv/www/htdocs/mediawiki-1.39.3/resources/assets/lexielogo.png
#    register: logo_exists

#  - name: Download logo image
#    ansible.builtin.get_url:
#      url: 
#      dest: /srv/www/htdocs/mediawiki-1.39.3/resources/assets/lexielogo.png
#    when: logo_exists.stat.exists == false

  - name: Add Logo to LocalSettings.php
    lineinfile:
      state: present
      dest: /srv/www/htdocs/mediawiki-1.39.3/LocalSettings.php
      regexp: "^\\s*'1x'"
      line: "'1x' => \"$wgResourceBasePath/resources/assets/lexielogo.png\","
